config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "tops#index"

  resources :shops
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 65_535 }

  def self.ransackable_attributes(_auth_object = nil)
    %w[title description area budget scene]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end

  # カスタム検索メソッドを定義
  def self.ransackable_scopes(_auth_object = nil)
    %i[budget_range]
  end

  # 予算が指定された範囲内であるかを確認するメソッド
  def self.budget_between(min_budget, max_budget)
    where('budget >= ? AND budget <= ?', min_budget, max_budget)
  end

  # パラメータから予算範囲を解析し、適切なスコープを適用
  def self.budget_range(range)
    min_budget, max_budget = range.split('-').map(&:to_i)
    budget_between(min_budget, max_budget)
  end

  # エリアに基づいてフィルタリングするメソッド
  def self.by_area(area)
    where(area: area)
  end

  # 利用用途に基づいてフィルタリングするメソッド
  def self.by_scene(scene)
    where(scene: scene)
  end

  # # 予算が指定された最小値以上であるかを確認するメソッド
  # def self.budget_gteq(min_budget)
  #   where('budget >= ?', min_budget)
  # end

  # # 予算が指定された最大値未満であるかを確認するメソッド
  # def self.budget_lteq(max_budget)
  #   where('budget < ?', max_budget)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @q = Shop.ransack(params[:q])
    if params[:budget_range]
      @shops = Shop.budget_range(params[:budget_range])
    elsif params[:area]
      @shops = Shop.by_area(params[:area])
    elsif params[:scene]
      @shops = Shop.by_scene(params[:scene])
    else
      @shops = @q.result(distinct: true).order(created_at: :desc)
    end
  end

  def show
    @shop = Shop.find(params[:id])
    @q = Shop.ransack(params[:q])
    @shops = @q.result(distinct: true).order(created_at: :desc)
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:title, :description, :area, :budget, :scene, :shop_image, :shop_image_cache)
  end

  # def autocomplete
  #   @shops = Shop.where("title like ?", "%#{params[:q]}%").limit(6)
  #   render partial: 'shops/autocomplete', locals: { shops: @shops }
  # end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @q = Shop.ransack(params[:q])
    @shops = @q.result(distinct: true).order(created_at: :desc).limit(9)
  end

  # def autocomplete
  #   @shops = Shop.where('title LIKE ?', "%#{params[:title]}%")
  #   respond_to do |format|
  #     format.json { render json: @shops.map(&:title) }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "シーシャ検索サイト" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/b5bf160816.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"></script>
  </head>

  <body class="font-sans">
    <%= render 'shared/header' %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_error_massage.html.erb
<div class="pt-16">
  <% if object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(object.errors.count, "error") %> prohibited this object from being saved:</h2>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/shared/_flash_message.html.erb
<div class="pt-16">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="fixed bottom-0 left-0 w-full bg-black text-white">
  <div class="flex items-center justify-between h-16">
    <nav class="items-center">
      <%= link_to "利用規約", "#", class: "text-white text-sm  ml-4" %>
      <%= link_to "プライバシーポリシー", "#", class: "text-white text-sm  ml-4" %>
      <%= link_to "お問い合わせ", "#", class: "text-white text-sm  ml-4" %>
    </nav>
    <aside class="text-white text-sm mr-4">シーシャ検索サイト｜name - ©</aside>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-black fixed top-0 left-0 w-full z-10">
  <div class="flex items-center justify-between h-16">
    <div class="flex ml-2 items-center">
      <%= image_tag("sample.png", alt: "ロゴ", class: "h-10") %>
      <a href="/" class="text-white text-2xl ml-4">シーシャ検索サイト</a>
    </div>
    <!-- ransack検索フォーム -->
    <div class="flex-grow">
      <%= search_form_for @q, url: shops_path, local: true, class: 'd-flex mx-auto my-2 my-lg-0 position-relative' do |f| %>
        <div data-controller="autocomplete" data-autocomplete-url-value="/shops/autocomplete" role="combobox">
          <div class="input-group">
            <%= f.search_field :title_or_description_or_area_or_budget_or_scene_cont, data: { autocomplete_target: 'input' }, placeholder: "店舗名で検索", class: "ml-4 w-100 h-10 px-4 bg-white text-black rounded-full" %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- Tailwind CSSを使用したハンバーガーメニューアイコンの追加 -->
    <div class="flex ml-auto">
      <nav>
        <ul class="flex space-x-4 text-white">
          <li><%= link_to 'ホーム', root_path %></li>
          <li><%= link_to '店舗一覧', shops_path%></li>
          <li><%= link_to '新規登録' %></li>
          <li><%= link_to 'ログイン' %></li>
        </ul>
      </nav>

      <button id="menu-toggle" class="text-white ml-4 mr-4 focus:outline-none">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M4 6h16M4 12h16m-7 6h7"></path>
        </svg>
      </button>
    </div>
  </div>
  <!-- ドロワーメニューの追加 -->
  <div id="drawer-menu" class="hidden absolute right-0 top-0 bg-black w-48 h-full">
    <a href="/" class="text-white block p-4">マイページ</a>
    <a href="/" class="text-white block p-4">ログアウト</a>
  </div>
</header>

app/views/shops/_autocomplete.html.erb
<% shops.each do |shop| %>
  <li class="list-group-item list-group-item-action" role="option" data-autocomplete-value="<%= shop.title %>" data-autocomplete-label="<%= shop.title %>">
    <%= shop.title %> - <%= shop.address %> <!-- 住所を追加 -->
  </li>
<% end %>

app/views/shops/_form.html.erb
<%= form_with model: @shop, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', rows: 10 %>
    </div>
    <div class="form-group">
      <%= f.label :shop_image %>
      <%= f.file_field :shop_image, class: 'form-control mb-3', accept: 'image/*' %>
      <%= f.hidden_field :shop_image_cache %>
    </div>
    <div class='mt-3 mb-3'>
      <%= image_tag @shop.shop_image.url, id: 'preview', size: '300x200' %>
    </div>

     <%= f.submit class: 'btn btn-primary' %>
  <% end %>

app/views/shops/_search_form.htnl.erb
<%= search_form_for @q, url: search_path, html: { method: :get } do |f| %>
<div class="w-full md:w-1/4 px-2 mb-4 md:mb-0">
          <div class="relative">
            <input type="text" placeholder="エリア" class="w-full px-4 py-2 pr-10 border rounded-lg"
                   id="search"
                   name="search">
            <span class="absolute left-3 top-1/2 transform -translate-y-1/2"></span>
          </div>
        </div>
        <div class="w-full md:w-1/4 px-2 mb-4 md:mb-0">
          <div class="relative">
            <input type="text" placeholder="予算" class="w-full px-4 py-2 pr-10 border rounded-lg">
            <span class="absolute left-3 top-1/2 transform -translate-y-1/2"></span>
          </div>
        </div>
        <div class="w-full md:w-1/4 px-2">
          <div class="relative">
            <input type="text" placeholder="利用用途" class="w-full px-4 py-2 pr-10 border rounded-lg">
            <span class="absolute left-3 top-1/2 transform -translate-y-1/2"></span>
          </div>
        </div>
        <div class="flex items-center right-3 px-2">
          <button class="ml-auto px-6 py-2 bg-black text-white rounded-lg">検索</button>
        </div><% end %>

app/views/shops/_shop.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="shop-id-<%= shop.id %>">
    <div class="card">
      <%= image_tag shop.shop_image_url, class: "card-img-top", width: "300", height:"200" %>
      <div class="card-body">
        <div class="d-flex">
          <h4 class="card-title">
            <%= link_to shop.title, shop_path(shop) %>
          </h4>
          <div class='ms-auto'>
            <%= link_to '#', id: "button-edit-#{shop.id}" do %>
              <i class="bi bi-pencil-fill"></i>
            <% end %>
            <%= link_to '#', id: "button-delete-#{shop.id}", method: :delete, data: {confirm: ''} do %>
              <i class="bi bi-trash-fill"></i>
            <% end %>
          </div>
        </div>
        <ul class="list-inline">
          <li><i class="bi bi-person"></i><%= shop.user.decorate.full_name %></li>
          <li><i class="bi bi-calendar"></i><%= l shop.created_at, format: :short %></li>
        </ul>
        <p class="card-text"><%= shop.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<!-- 掲示板一覧 -->
<% content_for :title do %>
  店舗一覧
<% end %>

<section class="bg-gray-100 text-gray-600 px-36">
  <div class="container px-4 py-12 mx-auto">
    <div class="flex flex-col text-center w-full mb-20 tracking-wider">
      <h1 class="text-5xl mb-4 text-gray-900">Store List</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">店舗一覧</p>
    </div>
    <div class="flex flex-wrap -m-4">
      <% if @shops.present? %>
        <% @shops.each do |shop| %>
          <div class="w-1/3 p-4">
            <div class="flex relative">
              <%= image_tag("shisha.jpg", class: "absolute inset-0 w-full h-full object-cover object-center rounded-xl") %>
              <div class="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100 rounded-xl">
                <h2 class="tracking-widest text-sm title-font font-medium text-indigo-500 mb-1"><%= shop.area %></h2>
                <h1 class="text-lg text-gray-900 mb-3"><%= link_to shop.title, shop_path(shop) %></h1>
                <p class="leading-relaxed title-font font-medium"><%= shop.description %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="w-full text-center">
          <p><%= t('shops.no_result') %></p>
        <% end %>
      </div>
    </div>
    <%# <%= paginate @shops %>
  </div>
  <div class="mb-16">
</section>

app/views/shops/show.html.erb
<div class="container mx-auto bg-gray-100 p-12 px-36">
  <div class="relative flex justify-center items-center">
    <%= image_tag("shisha.jpg", class: "w-960 h-480 object-cover rounded-xl") %>
    <div class="absolute inset-0 bg-opacity-50 flex flex-col justify-center items-center text-white">
    </div>
  </div>

<!-- app/views/shops/show.html.erb -->

<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl mb-6 pt-7">店舗情報</h1>

  <div class="bg-white shadow-md rounded-xl p-6">
    <div class="items-center mb-4 grid grid-cols-1 gap-6">
      <div>
        <p class="mb-2">店舗名</p>
        <p><%= @shop.title %></p>
      </div>

      <hr class="col-span-full my-2">

      <div>
        <p class="mb-2">利用用途</p>
        <p><%= @shop.scene %></p>
      </div>

      <hr class="col-span-full my-2">

      <div>
        <p class="mb-2">予算</p>
        <p><%= @shop.budget %>円</p>
        <p>詳細記載予定</p>
      </div>

      <hr class="col-span-full my-2">

      <div>
        <%# <i class="fas fa-phone text-gray-500 mr-2"></i> %>
        <p class="mb-2">電話番号</p>
        <p><%= @shop.shop_number %></p>
        <%# <p class="text-sm text-gray-500 mt-1">※電話予約の場合は</p> %>
      </div>

      <hr class="col-span-full my-2">

      <div>
        <p class="mb-2">エリア</p>
        <p><%= @shop.area %></p>
      </div>

      <hr class="col-span-full my-2">

      <div>
        <p class="mb-2">営業時間</p>
        <p><%= @shop.opening_hours %></p>
      </div>

      <hr class="col-span-full my-2">

      <div>
        <p class="mb-2">アクセス</p>
        <p>GoogleMap予定</p>
      </div>

      <hr class="col-span-full my-2">

      <div>
        <p class="mb-2">タグ</p>
        <p>タグ付け予定</p>
      </div>

        <%# <hr class="col-span-full my-2"> %>
    </div>
  </div>
</div>

app/views/tops/index.html.erb
<div class="container mx-auto bg-gray-100">
  <div class="relative">
    <%= image_tag("shisha.jpg", class: "w-1280 h-720 object-cover") %>
    <div class="absolute inset-0 bg-black bg-opacity-50 flex flex-col justify-center items-center text-white">
    </div>
  </div>

  <div class="container mx-auto px-36 py-8">
    <h1 class="text-5xl text-center mb-2 tracking-wider">SHISHA Search</h1>
    <p class="lg:w-2/3 mx-auto pb-8 leading-relaxed text-center tracking-wider">シーシャ屋を探す</p>

    <div class="bg-white rounded-lg shadow-md p-6">
      <div class="flex flex-wrap -mx-2 mb-4">
        <%= search_form_for @q, url: shops_path, local: true do |f| %>
          <%= f.search_field :area_cont, placeholder: "エリアで検索", class: "ml-2 w-100 h-10 px-4 bg-white text-black rounded-full border" %>
          <%= f.select :budget_range, [['~1,000円', '0-1000'], ['1,000~2,000円', '1000-2000'], ['2,000~3,000円', '2000-3000'], ['3,000~4,000円', '3000-4000'], ['4,000~5,000円', '4000-5000'], ['5,000円~', '5000+']], { prompt: "予算を選択" }, { class: "ml-2 w-100 h-10 px-4 bg-white text-black rounded-full border appearance-none" } %>
          <%= f.search_field :scene_cont, placeholder: "利用用途", class: "mr-3 ml-2 w-100 h-10 px-4 bg-white text-black rounded-full border" %>
          <%= f.submit "検索", class: "ml-auto px-6 py-2 bg-black text-white rounded-lg hover:bg-gray-700" %>
        <% end %>
      </div>

    <%# <div class="flex justify-center items-center mb-8">
      <button class="px-4 py-2 rounded-full border hover:bg-gray-100">エリアから探す</button>
      <button class="px-4 py-2 rounded-full border hover:bg-gray-100">予算から探す</button>
      <button class="px-4 py-2 rounded-full border hover:bg-gray-100">利用用途から探す</button>
    </div> %>

    <div class="mb-8">
      <div class="relative mx-auto">
        <%= search_form_for @q, url: shops_path, local: true do |f| %>
          <%= f.search_field :title_or_description_or_area_or_budget_or_scene_cont, placeholder: "渋谷, 2500, デート...", class: "w-full px-4 py-2 pr-10 border rounded-full" %>
          <button class="absolute right-3 top-1/2 transform -translate-y-1/2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
        </button>
        <% end %>
      </div>
    </div>

    <!-- _area.html.erbで表示予定 -->
    <div class="mb-8">
      <h2 class="text-xl mb-4">エリアから探す</h2>
      <div class="flex flex-wrap gap-4">
        <% [
          '恵比寿',
          '渋谷',
          '新宿',
          '池袋',
          '銀座',
          '六本木',
          '麻布十番',
          '表参道',
          '青山',
          '代官山',
          '恵比寿',
          '渋谷',
          '新宿',
          '池袋',
          '銀座',
          '六本木',
          '麻布十番',
          '表参道',
          '青山',
          '代官山'
        ].uniq.each do |area| %>
          <%= link_to area, shops_path(area: area), class: "px-4 py-2 rounded-full border hover:bg-gray-100" %>
        <% end %>
      </div>
    </div>

    <!-- _budget.html.erbで表示予定 -->
    <div class="mb-8">
      <h2 class="text-xl mb-4">予算から探す</h2>
      <div class="flex flex-wrap gap-4">
        <% [
          ['~1,000円', '0-1000'],
          ['1,000~2,000円', '1000-2000'],
          ['2,000~3,000円', '2000-3000'],
          ['3,000~4,000円', '3000-4000'],
          ['4,000~5,000円', '4000-5000'],
          ['5,000円~', '5000+'],
        ].each do |budget, range| %>
          <%= link_to budget, shops_path(budget_range: range), class: "px-4 py-2 rounded-full border hover:bg-gray-100" %>
        <% end %>
      </div>
    </div>


    <!-- _scene.html.erbで表示予定 -->
    <div>
      <h2 class="text-xl mb-4">利用用途から探す</h2>
      <div class="flex flex-wrap gap-4">
        <% [
          'デート',
          'ワーク',
          'ビジネス',
          'ゆっくり',
          'その他',
        ].each do |scene| %>
          <%= link_to scene, shops_path(scene: scene), class: "px-4 py-2 rounded-full border hover:bg-gray-100" %>
        <% end %>
      </div>
    </div>
  </div>

  <section class="text-gray-600">
    <div class="container px-4 py-12 mx-auto">
      <div class="flex flex-col text-center w-full mb-20 tracking-wider">
        <h1 class="text-5xl mb-4 text-gray-900">Store List</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">店舗一覧</p>
      </div>

      <section class="bg-gray-100 text-gray-600">
        <div class="container px-4 mx-auto">
          <div class="flex flex-wrap -m-4">
            <% if @shops.present? %>
              <% @shops.each do |shop| %>
                <div class="w-1/3 p-4">
                  <div class="flex relative">
                    <img alt="gallery" class="absolute inset-0 w-full h-full object-cover object-center" src="https://dummyimage.com/600x360">
                    <div class="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                      <div class="tracking-widest text-sm title-font font-medium text-indigo-500 mb-1" style="min-height: 60px;">
                        <%= shop.area.presence || "" %>
                      </div>
                      <h1 class="title-font text-lg font-medium text-gray-900 mb-3"><%= link_to shop.title, shop_path(shop) %></h1>
                      <p class="leading-relaxed"><%= shop.description %></p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <p>店舗が見つかりませんでした</p>
            <% end %>
          </div>
        </div>
      </section>

  <div class="text-center mt-8 mb-8">
    <button class="px-6 py-3 bg-black text-white rounded-full hover:bg-gray-700"><%= link_to 'もっとみる', shops_path %></button>
  </div>

  <div class="mb-16"></div>
</div>